export const MODULE_TYPE_CODES = {
  DON_HANG_DIEU_HANH: 'DHDH',
  DON_HANG_VAO_RA_CHUA_HOAN_THANH: 'DHVR_CHT',
  DON_HANG_VAO_RA_DA_HOAN_THANH: 'DHVR_DHT',
  DON_HANG_TRAM_CAN: 'DHTC',
  DON_HANG_XUAT_HANG: 'DHXH',
  DON_HANG_NHAP_HANG: 'DHNH',
  DON_HANG_KINH_DOANH: 'DHKD',
};
