// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT.CORE;

#nullable disable

namespace PROJECT.CORE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230622022948_Init_DB")]
    partial class Init_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdAccount", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserName");

                    b.HasIndex("GroupId");

                    b.ToTable("tblAdAccount");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdAccountGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblAdAccountGroup");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdAccountGroupRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RightId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RightId");

                    b.ToTable("tblAdAccountGroupRight");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("PId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RightId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblAdMenu");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdMessage", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("tblAdMessage");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdRight", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("PId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblAdRight");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdArea", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdArea");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdDepartment", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdDepartment");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdItem", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdItem");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdItemType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdItemType");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdMixer", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdMixer");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdModule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOrder")
                        .HasColumnType("int");

                    b.Property<string>("PId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tblMdModule");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdOrderType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdOrderType");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdPartner", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProvider")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdPartner");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdPourType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdPourType");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdSand", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdSand");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdStock", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdStock");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdStone", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdStone");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdUnit", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdUnit");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdVehicle", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Tonnage")
                        .HasColumnType("float");

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdVehicle");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.MD.tblMdVehicleType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblMdVehicleType");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.SO.tblStoreOrderOperating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AutoScaleOut")
                        .HasColumnType("bit");

                    b.Property<string>("CardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeExport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeStore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Confirm1")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm10")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm2")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm3")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm4")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm5")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm6")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm7")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm8")
                        .HasColumnType("int");

                    b.Property<int?>("Confirm9")
                        .HasColumnType("int");

                    b.Property<string>("Confirm9Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Confirm9Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountReindex")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DayCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryCodeParent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DriverAccept")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverPrintNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DriverPrintTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDDistributorSyn")
                        .HasColumnType("int");

                    b.Property<int?>("IndexOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IndexOrder1")
                        .HasColumnType("int");

                    b.Property<int?>("IndexOrder2")
                        .HasColumnType("int");

                    b.Property<int?>("IndexOrderTemp")
                        .HasColumnType("int");

                    b.Property<bool?>("IsScaleAuto")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSyncedByNewWS")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVoiced")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ItemId")
                        .HasColumnType("float");

                    b.Property<string>("ItemUnitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("LockInDbet")
                        .HasColumnType("bit");

                    b.Property<string>("LogHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogJobAttach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogProcessOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoocCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameDistributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameStore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteExport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberVoice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PackageNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Prioritize")
                        .HasColumnType("int");

                    b.Property<decimal?>("RealNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RealRequireNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonExport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shifts")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Step")
                        .HasColumnType("int");

                    b.Property<decimal?>("SumNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TimeConfirm1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm10")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm5")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm6")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm7")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm8")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirm9")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeConfirmHistory")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeIn21")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeIn22")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeIn33")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TransportMethodId")
                        .HasColumnType("int");

                    b.Property<string>("TransportMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Trough")
                        .HasColumnType("int");

                    b.Property<int?>("Trough1")
                        .HasColumnType("int");

                    b.Property<string>("TroughLineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeXK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WarningNotCall")
                        .HasColumnType("bit");

                    b.Property<int?>("WeightIn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WeightInTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WeightOut")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WeightOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("XiRoiAttatchmentFile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblStoreOrderOperating");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdAccount", b =>
                {
                    b.HasOne("PROJECT.CORE.Entities.AD.tblAdAccountGroup", "AccountGroup")
                        .WithMany("ListAccount")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("AccountGroup");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdAccountGroupRight", b =>
                {
                    b.HasOne("PROJECT.CORE.Entities.AD.tblAdAccountGroup", "AccountGroup")
                        .WithMany("ListAccountGroupRight")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJECT.CORE.Entities.AD.tblAdRight", "Right")
                        .WithMany("ListAccountGroupRight")
                        .HasForeignKey("RightId");

                    b.Navigation("AccountGroup");

                    b.Navigation("Right");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdAccountGroup", b =>
                {
                    b.Navigation("ListAccount");

                    b.Navigation("ListAccountGroupRight");
                });

            modelBuilder.Entity("PROJECT.CORE.Entities.AD.tblAdRight", b =>
                {
                    b.Navigation("ListAccountGroupRight");
                });
#pragma warning restore 612, 618
        }
    }
}
